// Code generated by atfield. DO NOT EDIT.

//+build !atfield

package define

import (
	"github.com/AkiOuma/atfield/example/a"
	"github.com/AkiOuma/atfield/example/b"
)

func AUserToBUser(source *a.User) *b.User {
	result := &b.User{}
	result.BirthDay = source.BirthDay
	result.ID = int32(source.Id)
	result.Name = []byte(source.UserName)
	result.Addr = source.Address
	result.RegisterTime = source.RegisterTime
	result.Labels = source.Labels
	result.PhoneNumber = source.PhoneNumber
	return result
}

func BulkAUserToBUser(source []*a.User) []*b.User {
	result := make([]*b.User, 0, len(source))
	for _, v := range source {
		result = append(result, AUserToBUser(v))
	}
	return result
}

func BUserToAUser(source *b.User) *a.User {
	result := &a.User{}
	result.Labels = source.Labels
	result.BirthDay = source.BirthDay
	result.Id = int64(source.ID)
	result.UserName = string(source.Name)
	result.Address = source.Addr
	result.RegisterTime = source.RegisterTime
	result.PhoneNumber = source.PhoneNumber
	return result
}

func BulkBUserToAUser(source []*b.User) []*a.User {
	result := make([]*a.User, 0, len(source))
	for _, v := range source {
		result = append(result, BUserToAUser(v))
	}
	return result
}
